name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        HASADNA_K8S_DEPLOY_KEY: ${{ secrets.HASADNA_K8S_DEPLOY_KEY }}
      run: |
        docker pull avidcovider/pipelines:latest &&\
        docker build --cache-from avidcovider/pipelines:latest -t avid-covider-pipelines . &&\
        if [ "${GITHUB_REF}" == "refs/heads/master" ]; then
          docker tag avid-covider-pipelines avidcovider/pipelines:latest &&\
          docker tag avid-covider-pipelines "avidcovider/pipelines:${GITHUB_SHA}" &&\
          echo "${DOCKER_HUB_PASSWORD}" | docker login -u "${DOCKER_HUB_USER}" --password-stdin &&\
          docker push avidcovider/pipelines:latest &&\
          docker push "avidcovider/pipelines:${GITHUB_SHA}" &&\
          cd `mktemp -d` &&\
          echo "${HASADNA_K8S_DEPLOY_KEY}" > hasadna_k8s_deploy_key &&\
          chmod 400 hasadna_k8s_deploy_key &&\
          export GIT_SSH_COMMAND="ssh -i hasadna_k8s_deploy_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" &&\
          git clone git@github.com:hasadna/hasadna-k8s.git &&\
          cd hasadna-k8s &&\
          python update_yaml.py '{"avidcovider":{"pipelinesImage":"avidcovider/pipelines:'${GITHUB_SHA}'"}}' ./values.auto-updated.yaml &&\
          git config --global user.name "Avid Covider Pipelines CI" &&\
          git config --global user.email "avid-covider-pipelines-ci@localhost" &&\
          git add ./values.auto-updated.yaml && git commit -m "automatic update of avid-covider pipelines" &&\
          git push origin master
        fi
